#!/usr/bin/env Rscript
# 90_export_overleaf.R — exporta tabelas (booktabs) e números citados (numbers.tex)
# para outputs/overleaf/. Nunca escreve prosa: só \newcommand e tabelas.
# Uso: Rscript scripts/90_export_overleaf.R
for (f in c("R/01_config.R", "R/02_utils.R")) source(f, encoding = "UTF-8")
out <- file.path(PATHS$outputs, "overleaf"); dir.create(file.path(out, "tables"), showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(out, "figures"), showWarnings = FALSE, recursive = TRUE)

tex_escape <- function(x) gsub("([%_&#])", "\\\\\\1", x)
to_booktabs <- function(dt, file, caption, label, digits = 2) {
  fmt <- function(v) if (is.numeric(v) && all(v == round(v), na.rm = TRUE)) format(v, big.mark = ",", scientific = FALSE, trim = TRUE) else if (is.numeric(v)) formatC(v, digits = digits, format = "f") else tex_escape(as.character(v))
  body <- apply(dt, 1, function(r) paste(r, collapse = " & "))
  cells <- as.data.table(lapply(dt, fmt)); body <- apply(cells, 1, paste, collapse = " & ")
  lines <- c("\\begin{table}[htbp]\\centering", sprintf("\\caption{%s}\\label{%s}", caption, label),
             sprintf("\\begin{tabular}{%s}", paste(rep("l", ncol(dt)), collapse = "")), "\\toprule",
             paste(tex_escape(names(dt)), collapse = " & "), "\\\\ \\midrule", paste0(body, " \\\\"), "\\bottomrule", "\\end{tabular}\\end{table}")
  writeLines(lines, file); invisible(file)
}

# ---- tabelas da sondagem ----
aud <- fread(file.path(PATHS$outputs, "probe", "auditoria_trajetorias.csv"))
to_booktabs(aud[, .(Court = tribunal, Class = classe_codigo, N = n_docs, Citation = p_com_citacao, Defense = p_com_defesa,
                    Judgment = p_com_sentenca, Appeal = p_com_recurso, Closure = p_com_baixa)],
            file.path(out, "tables", "audit_trajectories.tex"),
            "Share of cases with each reconstructed state (probe sample)", "tab:audit")
cov <- fread(file.path(PATHS$outputs, "probe", "cobertura_indice_por_tribunal_classe.csv"))
to_booktabs(cov[, .(Court = tribunal, Class = classe_codigo, `Index total` = total_indice, `No movements` = sem_movimentos,
                    `IBGE missing` = ibge_missing)], file.path(out, "tables", "coverage_index.tex"),
            "DataJud index totals by court and class (accessed 2026-09-04)", "tab:coverage", digits = 0)

# ---- numbers.tex: um \newcommand por número citado ----
num <- list(
  nProbeCourts     = uniqueN(cov$tribunal),
  nProbeDocsRandom = 11500,
  nNamedTrajectories = sum(aud$n_docs),
  tpuVersion       = format(as.Date(TPU$versao_data), "%d/%m/%Y"),
  probeDate        = "2026-09-04",
  totalDocsClass7  = sum(cov[classe_codigo == 7, total_indice]),
  totalDocsClass436 = sum(cov[classe_codigo == 436, total_indice])
)
mac <- sprintf("\\newcommand{\\%s}{%s}", names(num), vapply(num, function(v) if (is.numeric(v)) format(v, big.mark = ",", scientific = FALSE) else as.character(v), ""))
writeLines(c("% generated by scripts/90_export_overleaf.R — do not edit", mac), file.path(out, "numbers.tex"))
gjd_log(sprintf("export Overleaf: %d tabelas, %d macros em %s", 2L, length(num), out))
